# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Source\NESen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Source\NESen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Source\NESen\CMakeFiles D:\Source\NESen\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Source\NESen\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NESen

# Build rule for target.
NESen: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NESen
.PHONY : NESen

# fast build rule for target.
NESen/fast:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/build
.PHONY : NESen/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles\run.dir\build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/CPU.obj: src/CPU.cpp.obj
.PHONY : src/CPU.obj

# target to build an object file
src/CPU.cpp.obj:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/CPU.cpp.obj
.PHONY : src/CPU.cpp.obj

src/CPU.i: src/CPU.cpp.i
.PHONY : src/CPU.i

# target to preprocess a source file
src/CPU.cpp.i:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/CPU.cpp.i
.PHONY : src/CPU.cpp.i

src/CPU.s: src/CPU.cpp.s
.PHONY : src/CPU.s

# target to generate assembly for a file
src/CPU.cpp.s:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/CPU.cpp.s
.PHONY : src/CPU.cpp.s

src/Cartridge.obj: src/Cartridge.cpp.obj
.PHONY : src/Cartridge.obj

# target to build an object file
src/Cartridge.cpp.obj:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/Cartridge.cpp.obj
.PHONY : src/Cartridge.cpp.obj

src/Cartridge.i: src/Cartridge.cpp.i
.PHONY : src/Cartridge.i

# target to preprocess a source file
src/Cartridge.cpp.i:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/Cartridge.cpp.i
.PHONY : src/Cartridge.cpp.i

src/Cartridge.s: src/Cartridge.cpp.s
.PHONY : src/Cartridge.s

# target to generate assembly for a file
src/Cartridge.cpp.s:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/Cartridge.cpp.s
.PHONY : src/Cartridge.cpp.s

src/Common.obj: src/Common.cpp.obj
.PHONY : src/Common.obj

# target to build an object file
src/Common.cpp.obj:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/Common.cpp.obj
.PHONY : src/Common.cpp.obj

src/Common.i: src/Common.cpp.i
.PHONY : src/Common.i

# target to preprocess a source file
src/Common.cpp.i:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/Common.cpp.i
.PHONY : src/Common.cpp.i

src/Common.s: src/Common.cpp.s
.PHONY : src/Common.s

# target to generate assembly for a file
src/Common.cpp.s:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/Common.cpp.s
.PHONY : src/Common.cpp.s

src/NESen.obj: src/NESen.cpp.obj
.PHONY : src/NESen.obj

# target to build an object file
src/NESen.cpp.obj:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/NESen.cpp.obj
.PHONY : src/NESen.cpp.obj

src/NESen.i: src/NESen.cpp.i
.PHONY : src/NESen.i

# target to preprocess a source file
src/NESen.cpp.i:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/NESen.cpp.i
.PHONY : src/NESen.cpp.i

src/NESen.s: src/NESen.cpp.s
.PHONY : src/NESen.s

# target to generate assembly for a file
src/NESen.cpp.s:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/NESen.cpp.s
.PHONY : src/NESen.cpp.s

src/PPU.obj: src/PPU.cpp.obj
.PHONY : src/PPU.obj

# target to build an object file
src/PPU.cpp.obj:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/PPU.cpp.obj
.PHONY : src/PPU.cpp.obj

src/PPU.i: src/PPU.cpp.i
.PHONY : src/PPU.i

# target to preprocess a source file
src/PPU.cpp.i:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/PPU.cpp.i
.PHONY : src/PPU.cpp.i

src/PPU.s: src/PPU.cpp.s
.PHONY : src/PPU.s

# target to generate assembly for a file
src/PPU.cpp.s:
	$(MAKE) -f CMakeFiles\NESen.dir\build.make CMakeFiles/NESen.dir/src/PPU.cpp.s
.PHONY : src/PPU.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... install/local
	@echo ... install/strip
	@echo ... edit_cache
	@echo ... install
	@echo ... NESen
	@echo ... rebuild_cache
	@echo ... run
	@echo ... list_install_components
	@echo ... src/CPU.obj
	@echo ... src/CPU.i
	@echo ... src/CPU.s
	@echo ... src/Cartridge.obj
	@echo ... src/Cartridge.i
	@echo ... src/Cartridge.s
	@echo ... src/Common.obj
	@echo ... src/Common.i
	@echo ... src/Common.s
	@echo ... src/NESen.obj
	@echo ... src/NESen.i
	@echo ... src/NESen.s
	@echo ... src/PPU.obj
	@echo ... src/PPU.i
	@echo ... src/PPU.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

